package bev.and.owe;

import java.util.ArrayList;

public class PhrazesAndAnswers {
	private static ArrayList<String> phrases;
	private static ArrayList<String> mixedphrases;
	
	public PhrazesAndAnswers() {
		phrases = new ArrayList<String>();
		mixedphrases = new ArrayList<String>();
		
		mixedphrases.add("innate daze swerk");
		mixedphrases.add("tong inch eek");
		mixedphrases.add("sought indy dork");
		mixedphrases.add("ear lie beard");
		mixedphrases.add("strayed hays");
		mixedphrases.add("boo creep hort");
		mixedphrases.add("tack seed arrive her");
		mixedphrases.add("reef or he");
		mixedphrases.add("hex traitor rest or real");
		mixedphrases.add("app hell beeze");
		mixedphrases.add("hem urge hence see eggs hit");
		mixedphrases.add("bun knee rap hit");
		mixedphrases.add("bay course does in");
		mixedphrases.add("he dover heals");
		mixedphrases.add("whole door whores his");
		mixedphrases.add("nuke hid");
		mixedphrases.add("pie gout");
		mixedphrases.add("call if horn yeah");
		mixedphrases.add("color adore hot keys");
		mixedphrases.add("hit app hens");
		mixedphrases.add("A mare hick and ream");
		mixedphrases.add("take heal la");
		mixedphrases.add("mic done nulls");
		mixedphrases.add("what herb boat hull");
		mixedphrases.add("ten his bawl");
		mixedphrases.add("ties shoe bucks");
		mixedphrases.add("ream moat kin troll");
		mixedphrases.add("spike course cyst hem");
		mixedphrases.add("what herb head");
		mixedphrases.add("key pit top");
		mixedphrases.add("sung less is");
		mixedphrases.add("know con would");
		mixedphrases.add("chick cog ho hill annoy");
		mixedphrases.add("sock her go lea");
		mixedphrases.add("pill hock ace");
		mixedphrases.add("eve hill kin eve hill");
		mixedphrases.add("noose pop air heart hick el");
		mixedphrases.add("phase haul air");
		mixedphrases.add("pick turf fray em");
		mixedphrases.add("toy lets heat");
		mixedphrases.add("hell heck tron hick muse sick");
		mixedphrases.add("Hang herman age mint");
		mixedphrases.add("hail owe ink cost tomb");
		mixedphrases.add("reese hike hell been");
		mixedphrases.add("an hall hog claw hawk");
		mixedphrases.add("stray hinge will dorn hest");
		mixedphrases.add("cow itch pout ate hoe");
		mixedphrases.add("tyrant nose sore us her hex");
		mixedphrases.add("cough eek up");
		mixedphrases.add("wall con thebe each");
		mixedphrases.add("sky raise her");
		mixedphrases.add("tie doll way eve");
		mixedphrases.add("eye screams and witch");
		mixedphrases.add("bill gym waft hull");
		mixedphrases.add("pop lick lie berry");
		mixedphrases.add("rind noose sore rust");
		mixedphrases.add("pin hut but here hand jill he");
		mixedphrases.add("app hill he eve her half tore");
		mixedphrases.add("Duh hole he buy bill");
		mixedphrases.add("duh tight and hick");
		mixedphrases.add("unit heads stay tis hoove a mare hick uh");
		mixedphrases.add("come putt her sigh hence");
		mixedphrases.add("bear hack oh bomb huh");
		mixedphrases.add("add ham send lure");
		mixedphrases.add("goal dung ate burr edge");
		mixedphrases.add("ale burton stain");
		mixedphrases.add("sand tuck loss");
		mixedphrases.add("two oath fare he");
		mixedphrases.add("hem pie hearse tate bill ding");
		mixedphrases.add("huh why an eye lens");
		mixedphrases.add("pin seal hand pay pore");
		mixedphrases.add("pace if hick oh shin");
		mixedphrases.add("grey hen offs hand");
		mixedphrases.add("hats woots hes head");
		mixedphrases.add("her reek can cat re nuh");
		mixedphrases.add("tub heat tills");
		mixedphrases.add("police hand than cue");
		mixedphrases.add("mound tank lime more");
		mixedphrases.add("day leave item ins");
		mixedphrases.add("hem in hems");
		mixedphrases.add("low call noose pay purr");
		mixedphrases.add("furr root sand fetch tables");
		mixedphrases.add("hoe line won");
		mixedphrases.add("de cove hards");
		mixedphrases.add("whine heath up eww");
		mixedphrases.add("air heap otter");
		mixedphrases.add("rye sand shy en");
		mixedphrases.add("sly pea had");
		mixedphrases.add("boot he hand dub yeast");
		mixedphrases.add("too her deaf rants");
		mixedphrases.add("bat talk rye");
		mixedphrases.add("mast tour peas");
		mixedphrases.add("knew your cane keys");
		mixedphrases.add("goal den knack lice");
		mixedphrases.add("luck shore reek rews");
		mixedphrases.add("does hurt head eye land");
		mixedphrases.add("how tours pace");
		mixedphrases.add("den sing hen there ane");
		mixedphrases.add("edge jock hay shin");
		mixedphrases.add("ice cool");
		mixedphrases.add("half reek hand safe are he");
		mixedphrases.add("dock tour peep her");
		mixedphrases.add("pill lock haze");
		mixedphrases.add("fur stayed kite");
		mixedphrases.add("poll lease man");
		mixedphrases.add("get tars oh low");
		mixedphrases.add("moo femur a thin");
		mixedphrases.add("tea fee eden her");
		mixedphrases.add("a pin the hare");
		mixedphrases.add("hun door what her");
		mixedphrases.add("ion zip pries");
		mixedphrases.add("mine dawn there ode");
		mixedphrases.add("a soft paids");
		mixedphrases.add("pea an hope layer");
		mixedphrases.add("sow thieve the bore dur");
		mixedphrases.add("burr reed trash her");
		mixedphrases.add("miss own him pause able");
		mixedphrases.add("hemp tee hen did");
		mixedphrases.add("took lows fork come fort");
		mixedphrases.add("biz he has say bee fur");
		mixedphrases.add("hole door oars his");
		mixedphrases.add("moan key biz sinus");
		mixedphrases.add("boot hum doll her");
		mixedphrases.add("ease he has app hill pi");
		mixedphrases.add("wall con watt her");
		mixedphrases.add("oww tough biz hen us");
		mixedphrases.add("lea in audio dove in see");
		mixedphrases.add("my kill jag sun");
		mixedphrases.add("an jell he nuh joe lea");
		mixedphrases.add("lion are doe dick cap re hoe");
		mixedphrases.add("same mule hell jack sun");
		mixedphrases.add("just tin bee bore");
		mixedphrases.add("in app hill aid hay");
		mixedphrases.add("pore miss shin twos peak");
		mixedphrases.add("duh book key men");
		mixedphrases.add("spike king off thud if hill");
		mixedphrases.add("hear lea board gates the warm");
		mixedphrases.add("hem oh sin hull breaked own");
		mixedphrases.add("in dust real reef hole lew shin");
		mixedphrases.add("foe talk riff her");
		mixedphrases.add("cough fees hop");
		mixedphrases.add("dill liver he surf ice");
		mixedphrases.add("min he at your gulf");
		mixedphrases.add("door tee lit till sea crate");
		mixedphrases.add("rulings tones");
		mixedphrases.add("a brew ham link on");
		mixedphrases.add("mast her int does guys");
		mixedphrases.add("high dean goes eek");
		mixedphrases.add("a pin knees safe diss say pin he yarned");
		mixedphrases.add("win nine rum");
		mixedphrases.add("rays sore played");
		mixedphrases.add("app hill love my high");
		mixedphrases.add("peek cup lion");
		mixedphrases.add("sty reef home");
		mixedphrases.add("bob hill wrap");
		mixedphrases.add("nay tiff um hair hick an");
		mixedphrases.add("an hum mighted moo fee");
		mixedphrases.add("store bugs cough he");
		mixedphrases.add("mic key them house");
		mixedphrases.add("thee tree musk hit ears");
		mixedphrases.add("purr sun hull trey nor");
		mixedphrases.add("each hip shun peer mitts");
		mixedphrases.add("pow still off his");
		mixedphrases.add("bot he bill door");
		mixedphrases.add("mao hint eff her wrist");
		mixedphrases.add("life hing hone ape rare");
		mixedphrases.add("tuck seed hoe soot");
		mixedphrases.add("butter save thin sore rye");
		mixedphrases.add("furs pry or it he");
		mixedphrases.add("pie ruts boot he");
		mixedphrases.add("saw fast a bay bees boat hum");
		mixedphrases.add("laws hand gel his");
		mixedphrases.add("hair poured term in hull");
		mixedphrases.add("sack coned con chess");
		mixedphrases.add("gnat shin hull sick your itty");
		mixedphrases.add("tell hip pour tea shin");
		mixedphrases.add("gnat shin hull moan you mint");
		mixedphrases.add("eek whip mint");
		mixedphrases.add("read dot chill heep hip purse");
		mixedphrases.add("hull hid hay vick hay shin");
		mixedphrases.add("seek rat surf hiss");
		mixedphrases.add("gray tall hove chin nah");
		mixedphrases.add("thug rate hicks cape");
		mixedphrases.add("hop list aid hick shin");
		mixedphrases.add("bun dill love hun");
		mixedphrases.add("day lee hex hearse eyes");
		mixedphrases.add("pry fat an vast hig ate tour");
		mixedphrases.add("ace straw knot");
		mixedphrases.add("in terse stayed high weigh");
		mixedphrases.add("knot he buy nate sure");
		mixedphrases.add("heat turn it he");
		mixedphrases.add("pear king struck sure");
		mixedphrases.add("click kit tore tic hit"); //maybe should be removed
		mixedphrases.add("move he tray lore");
		mixedphrases.add("sitch you ate shin hull come hid ey");
		mixedphrases.add("trough bill may curr");
		mixedphrases.add("back crowned in firm mate shin");
		mixedphrases.add("press hid dent hell lick shuns");
		mixedphrases.add("ape hill jews");
		mixedphrases.add("hair plain pie lit");
		mixedphrases.add("boat hilled what her");
		mixedphrases.add("may pill sear up");
		mixedphrases.add("off his sick rat hairy");
		mixedphrases.add("ray kneed hay");
		mixedphrases.add("think cod hits fry day");
		mixedphrases.add("or bit hing sat hill light");
		mixedphrases.add("matt him attics");
		mixedphrases.add("pour form hence in hand singed rugs");
		mixedphrases.add("league hull had vice");
		mixedphrases.add("oh tell rum surf his");
		mixedphrases.add("hop tickle luge shin");
		mixedphrases.add("hit tally in sew duh");
		mixedphrases.add("thug rate gets be");
		mixedphrases.add("fool he fish hint core");
		mixedphrases.add("bee lows hero");
		mixedphrases.add("day lea fork hast");
		mixedphrases.add("jean gull bills");
		mixedphrases.add("loaf fat furs sighed");
		mixedphrases.add("suck carp hunch");
		mixedphrases.add("know won lie cue");
		mixedphrases.add("can deke hain");
		mixedphrases.add("kuh ream huve duck rop");
		mixedphrases.add("crit hick hull cone dish shin");
		mixedphrases.add("fay till acid hint");
		mixedphrases.add("pen key prom his");
		mixedphrases.add("bowls sigh");
		mixedphrases.add("pudge ham muzz");
		mixedphrases.add("sat herd hay mourn hing car tunes");
		mixedphrases.add("purr ficked tie ming");
		mixedphrases.add("fast shin nab lee laid");
		mixedphrases.add("Amp low ye hove them umph");
		mixedphrases.add("why hilled must hang");
		
		phrases.add("In a day's work");
		phrases.add("Tongue in cheek");
		phrases.add("Shot in the dark");
		phrases.add("Early bird");
		phrases.add("Straight A's");
		phrases.add("Book report");
		phrases.add("Taxi driver");
		phrases.add("Referee");
		phrases.add("Extra terrestrial");
		phrases.add("Applebees");
		phrases.add("Emergency exit");
		phrases.add("Bunny rabbit");
		phrases.add("Baker's dozen");
		phrases.add("Head over heels");
		phrases.add("Hold your horses");
		phrases.add("New kid");
		phrases.add("Pig out");
		phrases.add("California");
		phrases.add("Colorado Rockies");
		phrases.add("It happens");
		phrases.add("American dream");
		phrases.add("Tequila");
		phrases.add("McDonalds");
		phrases.add("Water bottle");
		phrases.add("Tennis ball");
		phrases.add("Tissue box");
		phrases.add("Remote control");
		phrases.add("Speaker system");
		phrases.add("Waterbed");
		phrases.add("Keep it up");
		phrases.add("Sunglasses");
		phrases.add("Knock on wood");
		phrases.add("Chicago, Illinois");
		phrases.add("Soccer goalie");
		phrases.add("Pillowcase");
		phrases.add("Evil Kinieval");
		phrases.add("Newspaper article");
		phrases.add("Facial hair");
		phrases.add("Picture frame");
		phrases.add("Toilet seat");
		phrases.add("Electronic music");
		phrases.add("Anger management");
		phrases.add("Halloween costume");
		phrases.add("Recycle bin");
		phrases.add("Analog clock");
		phrases.add("Strange wilderness");
		phrases.add("Couch potato");
		phrases.add("Tyrannosaurus rex");
		phrases.add("Coffee cup");
		phrases.add("Walk on the beach");
		phrases.add("Ski racer");
		phrases.add("Tidal wave");
		phrases.add("Ice cream sandwich");
		phrases.add("Belgium waffle");
		phrases.add("Public library");
		phrases.add("Rhinoceros");
		phrases.add("Peanut butter and jelly");
		phrases.add("Happily ever after");
		phrases.add("The holy bible");
		phrases.add("The Titanic");
		phrases.add("United States of America");
		phrases.add("Computer science");
		phrases.add("Barack Obama");
		phrases.add("Adam Sandler");
		phrases.add("Golden Gate Bridge");
		phrases.add("Albert Einstein");
		phrases.add("Santa Claus");
		phrases.add("Tooth fairy");
		phrases.add("Empire state building");
		phrases.add("Hawaiian islands");
		phrases.add("Pencil and paper");
		phrases.add("Pacific Ocean");
		phrases.add("Grain of sand");
		phrases.add("That's what she said");
		phrases.add("The Beatles");
		phrases.add("Hurricane Katrina");
		phrases.add("Please and thank you");
		phrases.add("Mountain climber");
		phrases.add("Daily vitamins");
		phrases.add("M&M's");
		phrases.add("Local newspaper");
		phrases.add("Fruits and vegetables");
		phrases.add("Hole in one");
		phrases.add("Deck of cards");
		phrases.add("Winnie the pooh");
		phrases.add("Harry Potter");
		phrases.add("Rise and shine");
		phrases.add("Sleepy head");
		phrases.add("Beauty and the beast");
		phrases.add("Tour de France");
		phrases.add("Battle cry");
		phrases.add("Masterpiece");
		phrases.add("New York Yankees");
		phrases.add("Golden necklace");
		phrases.add("Luxury cruise");
		phrases.add("Deserted Island");
		phrases.add("Outer space");
		phrases.add("Dancing in the rain");
		phrases.add("Education");
		phrases.add("High school");
		phrases.add("African safari");
		phrases.add("Doctor Pepper");
		phrases.add("Pillow case");
		phrases.add("First aid kit");
		phrases.add("Policeman");
		phrases.add("Guitar solo");
		phrases.add("Movie marathon");
		phrases.add("TV dinner");
		phrases.add("Up in the air");
		phrases.add("Under water");
		phrases.add("Eye on the prize");
		phrases.add("Mind on the road");
		phrases.add("Ace of spades");
		phrases.add("Piano player");
		phrases.add("South of the border");
		phrases.add("Buried treasure");
		phrases.add("Mission impossible");
		phrases.add("Empty handed");
		phrases.add("Too close for comfort");
		phrases.add("Busy as a beaver");
		phrases.add("Hold your horses");
		phrases.add("Monkey business");
		phrases.add("Bottom dollar");
		phrases.add("Easy as apple pie");
		phrases.add("Walk on water");
		phrases.add("Out of business");
		phrases.add("Leonardo Da Vinci");
		phrases.add("Michael Jackson");
		phrases.add("Angelina Jolie");
		phrases.add("Leonardo DiCaprio");
		phrases.add("Samuel L. Jackson");
		phrases.add("Justin Bieber");
		phrases.add("An apple a day");
		phrases.add("Permission to speak");
		phrases.add("The boogeyman");
		phrases.add("Speaking of the devil");
		phrases.add("Early bird gets the worm");
		phrases.add("Emotional breakdown");
		phrases.add("Industrial revolution");
		phrases.add("Photographer");
		phrases.add("Coffee shop");
		phrases.add("Delivery service");
		phrases.add("Miniature golf");
		phrases.add("Dirty little secret");
		phrases.add("Rolling stones");
		phrases.add("Abraham Lincoln");
		phrases.add("Master in disguise");
		phrases.add("Hide and go seek");
		phrases.add("A penny saved is a penny earned");
		phrases.add("When in Rome");
		phrases.add("Razorblade");
		phrases.add("Apple in my eye");
		phrases.add("Pick up line");
		phrases.add("Styrofoam");
		phrases.add("Bubble wrap");
		phrases.add("Native American");
		phrases.add("Animated movie");
		phrases.add("Starbucks Coffee");
		phrases.add("Mickey the mouse");
		phrases.add("The three musketeers");
		phrases.add("Personal trainer");
		phrases.add("Egyptian pyramids");
		phrases.add("Postal office");
		phrases.add("Body builder");
		phrases.add("Mount everest");
		phrases.add("Living on a prayer");
		phrases.add("Tuxedo suit");
		phrases.add("Better safe than sorry");
		phrases.add("First priority");
		phrases.add("Pirate's booty");
		phrases.add("Soft as a baby's bottom");
		phrases.add("Los Angeles");
		phrases.add("Airport terminal");
		phrases.add("Second conscious");
		phrases.add("National security");
		phrases.add("Teleportation");
		phrases.add("National monument");
		phrases.add("Equipment");
		phrases.add("Red hot chili peppers");
		phrases.add("Holiday vacation");
		phrases.add("secret service");
		phrases.add("Great wall of China");
		phrases.add("The great escape");
		phrases.add("Hopeless addiction");
		phrases.add("Bundle of fun");
		phrases.add("Daily Exercise");
		phrases.add("Private investigator");
		phrases.add("Astronaut");
		phrases.add("Interstate highway");
		phrases.add("Naughty by nature");
		phrases.add("Eternity");
		phrases.add("Parking structure");
		phrases.add("Click it or ticket");
		phrases.add("Movie trailer");
		phrases.add("Situational comedy");
		phrases.add("Troublemaker");
		phrases.add("Background information");
		phrases.add("Presidential elections");
		phrases.add("Apple juice");
		phrases.add("Airplane pilot");
		phrases.add("Bottled water");
		phrases.add("Maple syrup");
		phrases.add("Office secretary");
		phrases.add("Rainy day");
		phrases.add("Thank god it's friday");
		phrases.add("Orbiting satellite");
		phrases.add("Mathematics");
		phrases.add("Performance enhancing drugs");
		phrases.add("Legal advice");
		phrases.add("Hotel room service");
		phrases.add("Optical illusion");
		phrases.add("Italian soda");
		phrases.add("The Great Gatsby");
		phrases.add("Fuel efficient car");
		phrases.add("Below zero");
		phrases.add("Daily forecast");
		phrases.add("Jingle bells");
		phrases.add("Love at first site");
		phrases.add("Sucker punch");
		phrases.add("No one like you");
		phrases.add("Candy cane");
		phrases.add("Cream of the crop");
		phrases.add("Critical condition");
		phrases.add("Fatal accident");
		phrases.add("Pinky promise");
		phrases.add("Bullseye");
		phrases.add("Pajamas");
		phrases.add("Saturday morning cartoons");
		phrases.add("Perfect timing");
		phrases.add("Fashionably late");
		phrases.add("Employee of the month");
		phrases.add("Wild mustang");
	}
	
	public ArrayList<PhrazePack> getAllPhrazes() {
		ArrayList<PhrazePack> list = new ArrayList<PhrazePack>();
		for (int i = 0; i < phrases.size(); i++) {
			list.add(new PhrazePack(phrases.get(i), mixedphrases.get(i)));
		}
		return list;
	}

}
